<<<<<<< HEAD
version: '3.9'

services:
  app:
    build: ./backend
    ports:
      - 8080:8080
  bot-uwu:
    build: ./wordle-bot
    environment:
      - ENV=prod
    links:
      - app
=======
version: "3.9"
services:
  app:
    container_name: app
    build: ./backend
    image: app
    ports:
      - 8080:8080
  tacsfront:
    container_name: tacsfront
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
>>>>>>> development
